<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BemEstar.Dica.Models\BemEstar.Dica.Models.csproj" />
    <ProjectReference Include="..\BemEstar.Infra\BemEstar.Dica.Infra.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>07391cb4-a683-484a-935f-29135ab5ebde</UserSecretsId>
  </PropertyGroup>
</Project>